import "./globals.css";
import React from "react";
import Loader from "./Loader"; // Import the Loader component

export const metadata = {
  title: "The Jatin Singh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Loader/>
          {children}
      </body>
    </html>
  );
}
